name: Laravel Test

on:
  workflow_call:
    inputs:
      operating_system:
        description: The Operating System
        type: string
        required: true
        default: ubuntu-latest
      php_version:
        description: The PHP version
        type: string
        required: true
      laravel_version:
        description: The Laravel version
        type: string
        required: true
      branch:
        description: The branch or git reference
        type: string
        required: false


jobs:
  test_laravel:
    name: Laravel ${{ inputs.laravel_version }} (PHP ${{ inputs.php_version }})
    runs-on: ${{ inputs.operating_system }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}

      - name: Setup PHP with Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php_version }}

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ inputs.operating_system }}-php-${{ inputs.php_version }}-laravel-${{ inputs.laravel_version }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ inputs.operating_system }}-php-${{ inputs.php_version }}-laravel-${{ inputs.laravel_version }}-
            ${{ inputs.operating_system }}-php-${{ inputs.php_version }}-laravel-
            ${{ inputs.operating_system }}-php-
            ${{ inputs.operating_system }}-

      - name: Install Laravel
        run: composer require "laravel/framework:${{ inputs.laravel_version }}" --prefer-dist --no-progress --no-plugins

      - name: Update Composer dependencies
        run: composer update --prefer-dist --no-progress --no-suggest --optimize-autoloader --no-plugins

      - name: Run tests
        run: vendor/bin/phpunit
